const REDUCER_CONSTANTS = {
    SOCKET_CREATE_INSTANCE: "SOCKET_CREATE_INSTANCE",
    SOCKET_CHANGE_ACTIVE_INSTANCE: "SOCKET_CHANGE_ACTIVE_INSTANCE",
    SOCKET_SET_INSTANCE_STATUS: "SOCKET_SET_INSTANCE_STATUS",
    SOCKET_SET_INSTANCE_URI: "SOCKET_SET_INSTANCE_URI",
    SOCKET_SET_INSTANCE_OPTS: "SOCKET_SET_INSTANCE_OPTS",
} as const;

export default REDUCER_CONSTANTS;
